spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c1p52qjgvteo.us-east-1.rds.amazonaws.com:5432/capstone
    username: postgres
    password: cano1234
  servlet:
    multipart:
      max-file-size: 50MB
